### PR TITLE
The Fast and the Furious: Tokyo Slide

### PR DESCRIPTION
**Pull request by bretsky**
Best slider

### CODE REVIEW

**Comment by bretsky** [comment]
I have no idea if this actually works or not since I don't have the Arduino to test it anymore.

**Comment by Mogball** [comment]
We can debug later, I'll test it out if I have time and merge otherwise we can deal with it later

Also could we add like a label that shows the numerical value of each slider? Like not just when it stops but as its sliding, so that we know what value we're at or sliding towards

**Comment by Mogball** [comment]
oh and you'll need the corresponding changes in the sam repo, don't worry about testing just write the code and pretend it works

**Comment by bretsky** [comment]
I'll upload the SAM changes today

**Pull request merged**
