### PR TITLE
Fix errors with user input.

### PR DESCRIPTION
**Pull request by wyxzou**

### CODE REVIEW

**Comment by sadmansk** [comment]
Still failing when Up instruction is deployed:
```
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
Segmentation fault (core dumped)
```

**Comment by wyxzou** [comment]
screenshot 2017-05-30 19 09 21
screenshot 2017-05-30 19 08 36

So here's the output when I deploy Up instruction and the error message.

I do get `QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)` But no segfault.

**Comment by sadmansk** [comment]
it is likely not showing up as a result of you using an older compiler. What compiler are you using?

**Comment by wyxzou** [comment]
I'm not sure who, but the changes that were made in this commit seems to have already been merged into develop. The errors I was getting is no longer occurs in develop when I try testing it.

**Comment by sadmansk** [comment]
It's probably because you pulled in changes from jeff's unmerged branch, whose commits were squashed. I also reverted a change on the configuration file that jeff made, that might have been the root of the problem.

**Pull request closed without merging**
