### PR TITLE
Add camera setup documentation

### PR DESCRIPTION
**Pull request by jingyli**
Basic cameral setup documentations.
Left a placeholder for issues that may occur in the future.

### CODE REVIEW

**Comment by sadmansk** [comment]
This should be made as part of the wiki? What do you think @aneedalie?

**Comment by aneedalie** [comment]
Yes, please add this into the Wiki!

**Comment by jingyli** [comment]
I tried to clone the repository's wiki via cmd, and it is denying my access. I also can't seem to switch over to the wiki tab on the browser version.

**Comment by aneedalie** [comment]
That's really strange... I'm going to check your permissions but I don't think that should be happening. I know I can definitely do that but my permissions might be different from yours.

**Comment by aneedalie** [comment]
@jingyli Can you try again? I added the Controls team to this repo so it should give you at least collaborator access (which allows you to change Wikis).

**Comment by sadmansk** [comment]
Closed since it got added to the wiki instead.

**Pull request closed without merging**
