### PR TITLE
Skeleton classes for scripting

### PR DESCRIPTION
**Pull request by sadmansk**

### CODE REVIEW

**Comment by sadmansk** [comment]
oh didnt realize that there was a conflict after a recent PR. I'll rebase and fix it.

**Comment by sadmansk** [comment]
@tammy conflict is resolved, take a look, let's land this as soon as we can.

**Comment by sadmansk** [comment]
@aneedalie is there anything else? otherwise I'll just merge the changes once these are resolved.

**Comment by aneedalie** [comment]
That's it! :)

**Pull request merged**
