### PR TITLE
Added rotation

### PR DESCRIPTION
**Pull request by bretsky**

### CODE REVIEW

**Comment by Mogball** [comment]
@bretsky can you do a rebase against master?

**Comment by bretsky** [comment]
@Mogball Where there are conflicts, I'm assuming I should go with your newer changes right?

**Comment by Mogball** [comment]
yeah but you'd just need to copy in your stuff

**Comment by Mogball** [comment]
resolving the conflicts should be easy but git is dumb

**Comment by bretsky** [comment]
Okay I thought I did it right, but now my branch is all weird. What do

**Comment by Mogball** [comment]
Weird in what way .-.

**Comment by Mogball** [comment]
Uh don't worry about it good enough for me to figure how to merge lol

**Comment by Mogball** [comment]
okay I fixed it in the other PR but I have one main comment:
the timed rotation logic shouldn't be in `Preprocessor`; it should not be emitting signals back to the UI. Add a timer in `ImageViewer` and handle it the same way as the fps timer.

i.e. Preprocessor should only receive an `update_rotation` or whatever

**Comment by Mogball** [comment]
you can either add that here or PR against my branch I used to hack my way around git xd

**Comment by bretsky** [comment]
Alright, can you show me how to do that rebase stuff on Monday?

**Comment by Mogball** [comment]
sure

**Pull request closed without merging**
