### PR TITLE
Add my name to about dialog

### PR DESCRIPTION
**Pull request by bretsky**
Added my name to the contributor list in the about dialog.

add name

### CODE REVIEW

**Comment by wyxzou** [comment]
Mind if I just made the changes to my pull request "Make about dialog prettier?"

**Comment by bretsky** [comment]
@wyxzou If you merge your changes first, I can just make my edit after since it's pretty minor.

**Comment by wyxzou** [comment]
Yup sounds good.

**Comment by sadmansk** [comment]
Hey @bretsky, so now that there are conflicts in one of the files, you want to update your develop branch and rebase against that, again, the instructions of how to do that should be in the collaboration section of `CONTRIBUTING.md`

**Comment by bretsky** [comment]
@sadmansk I did the force push like you said, and it appears to have worked. Unfortunately because of some changes to the repository I can no longer build the project with Qt Creator, and thus I can't test to ensure that my name has been added properly.

**Pull request merged**
