### PR TITLE
Add action about window

### PR DESCRIPTION
**Pull request by ahmedsabie**
Addresses issue #19 

This is what the about window looks like
about

The only issue is clicking the hyperlink (this is made through the built-in html of text browswer) make all of text disappears because I get an error "No document for https://github.com/uwnrg/". It seems to be linking locally rather than to the internet. Any ideas?

### CODE REVIEW

**Comment by sadmansk** [comment]
looks like you have to enable external links: 
http://stackoverflow.com/questions/2465413/qt-add-a-hyperlink-to-a-dialog

**Comment by ahmedsabie** [comment]
Should be good now!

**Comment by sadmansk** [comment]
Okay, I'll pull your branch and try out the changes.

**Comment by sadmansk** [comment]
@ahmedsabie okay so a few points:
- Names should be the same size as the other text
- Needs to be more aesthetically pleasing, try adding margins around the text area, set a fixed size for the window so that all the text fits inside, etc.

**Comment by ahmedsabie** [comment]
This is what the new window looks like
pic

**Comment by sadmansk** [comment]
this is a lot better. just one last thing: change the font of the contributor list so it looks the same as the description. Also, rebase and sqaush the commits, and ping me once that's done, I'll merge it.

**Comment by ahmedsabie** [comment]
How do i squash the commits if ive already comitted two?

**Comment by sadmansk** [comment]
@ahmedsabie a simple google search yielded this: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by sadmansk** [comment]
I'd much rather have @aneedalie to take a look here to evaluate the aesthetic value.

**Comment by sadmansk** [comment]
also, as reference, this is what the firefox about dialog looks like:
selection_007

**Comment by aneedalie** [comment]
I think we can look at style in another PR. For now we can merge this and I'll comment on the aesthetics after. How does that sound? 😄

**Comment by sadmansk** [comment]
@aneedalie I'm okay with that.

@ahmedsabie I'll merge after you rebase and squash, you are probably looking for this command: `$ git rebase -i upstream/develop`.

**Comment by ahmedsabie** [comment]
@sadmansk I changed the font and squashed the commits, i hope i did that correctly not too familiar with working from a fork
p0

**Comment by sadmansk** [comment]
Almost done, just need to rebase against the develop branch, since there may be conflicts. Try doing: `git rebase https://github.com/uwnrg/minotaur-cpp develop`

**Comment by ahmedsabie** [comment]
i fixed the conflicts but unfortunately no matter what i do im back to getting errors when i run the project in QT, even when applying the fix i used before (removing the C++11 compiler in minotaur.pro)

**Comment by aneedalie** [comment]
I tried cloning and running it locally. I'm also getting errors when running Qt though they mostly look like they're platform specific errors, but they are very weird (attached below). I can `make` and run it fine otherwise though.

qt

**Comment by sadmansk** [comment]
@ahmedsabie what error are you getting?

**Comment by ahmedsabie** [comment]
p1

**Comment by sadmansk** [comment]
@ahmedsabie did you try cleaning your build directory and rebuilding?

**Comment by ahmedsabie** [comment]
@sadmansk  yeah no luck with that either, i even tried the old minotaur.pro file that first worked with QT but that's not working now either. I'll try my luck with Ubuntu then?

**Comment by sadmansk** [comment]
@ahmedsabie what version of Qt creator are you using? @aneedalie solved a problem she was having by upgrading to qt 5.8, maybe try the same?

**Comment by sadmansk** [comment]
@ahmedsabie how's this coming along?

**Comment by aneedalie** [comment]
I ran this on my local machine and it works fine. Just fixed merge conflicts and waiting for the build to pass.

**Comment by aneedalie** [comment]
@sadmansk could you help take a look at the error? I can run it fine locally.

**Comment by aneedalie** [comment]
Nevermind, I fixed it and it passed. 😄

**Pull request merged**
